---
title: "in-vitro meat"
author: "EH"
layout: post
date: "22 December 2017"
output: html_document
---

# in-vitro meat

Meat products contribute to almost one-third of humanity’s protein intake<font size="1"><sup>1</sup></font>. With population growth and increasing global wealth, meat production will have to increase by 200 million tonnes by 2050 to meet increasing demand<font size="1"><sup>2</sup></font>. However, the livestock sector is a significant contributor to environmental and human health problems and therefore safely and sustainably satisfying this demand will be a challenge. Innovative technologies such as lab cultured or in-vitro meat, have the potential to provide an alternative to conventional meat production. This document summarises the advantages and disadvantages of in-vitro meat and considers potential policy actions.

# meat production as we know it

The livestock sector is globally important. It employs 1.3 billion people worldwide of which 600 million are smallholder farmers in the developing world<font size="1"><sup>3</sup></font>. It has a global value of $1.4 trillion<font size="1"><sup>4</sup></font>, accounting for 40% of agricultural gross domestic product1. Livestock products make up 33% of protein consumption globally<font size="1"><sup>5</sup></font> and in the UK, government nutritional guidelines include meat as a source of protein for a healthy and balanced diet<font size="1"><sup>6</sup></font>. However, meat production poses a threat to both the environment and to public health. Livestock farming is currently the single largest anthropogenic user of land. Occupying a total area equivalent to 26% of the planet’s land surface it accounts for 70% of all agricultural land, 33% of which is used for animal feed alone<font size="1"><sup>1</sup></font>. Through land-use change, the livestock sector is also responsible for 14.5% of global greenhouse gas emissions making it the second largest contributor to greenhouse gas emissions after the burning of fossil fuels<font size="1"><sup>7</sup></font>. Water use by the livestock sector is also substantial with livestock rearing in the UK accounting for 119 million m<sup>3</sup> of water<font size="1"><sup>8</sup></font>. Public health implications of meat production are a further concern. For instance, antibiotic resistance is worsened by the high use of antibiotics in agriculture<font size="1"><sup>9,10</sup></font> with around 45% of antibiotic use within the UK in farm animals<font size="1"><sup>11</sup></font>. Additionally, two of the world’s most serious viral outbreaks in recent years can be attributed to livestock farming<font size="1"><sup>12,13</sup></font>. In light of this, the UK government is committed to sustainably meeting increasing protein demand whilst minimising environmental and human health impacts. One way it aims to achieve this is through the development of new food technologies<font size="1"><sup>14</sup></font>.

# in-vitro meat

One innovative approach that could support the sustainable intensification of agriculture is in-vitro meat production. This technology makes use of techniques in stem cell science and tissue engineering to cultivate meat outside of an animal. Muscle derived stem cells are isolated and cultured under controlled conditions where they proliferate into muscle tissue. Once mature, the new tissue can be harvested into an edible product<font size="1"><sup>15,16</sup></font>. As an alternative protein source, in-vitro meat offers a number of advantages. With no live animals required for production, the spread of animal-borne diseases should be prevented<font size="1"><sup>17</sup></font>. Furthermore, strict control over the manufacturing process has the potential to enable products to be nutritionally enhanced. Therefore, in-vitro meat could therefore provide the equivalent nutritional value of conventional meat and therefore satisfy UK government nutritional guidelines<font size="1"><sup>6,18</sup></font>. Environmental benefits are also promising. UK based research suggests that in-vitro meat production could produce up to 78-96% less greenhouse gas emissions, require 99% less land and use 82-96% less water than conventional meat production<font size="1"><sup>19</sup></font>. However, analyses in this study make assumptions based on the industrial processes used for scaling up in-vitro meat production. Follow up analyses predict higher levels of energy use than conventional meat production<font size="1"><sup>20</sup></font>. highlighting the large amount of uncertainty in these predictions<font size="1"><sup>21</sup></font>.

# policy considerations

The in-vitro meat research field remains small. Currently, there are around 50 researchers globally working on the development of in-vitro meat<font size="1"><sup>22</sup></font>. with privately funded start-up companies also beginning to emerge<font size="1"><sup>23,24,25</sup></font>. Despite this, since the development of the first synthetic hamburger in 2013, notable progress has been made. In 2015, the first artificial meatballs were unveiled, and in March 2017, California based Memphis Meats produced the first lab cultured chicken and duck<font size="1"><sup>26</sup></font>. However, the technology required to mass produce cultured meat is not yet available and production costs remain high. Memphis Meats report a value of around £31,000/kg beef<font size="1"><sup>27</sup></font>., although this is substantially less than the £218,000 burger unveiled in 2013<font size="1"><sup>28</sup></font>. For cultured meat production to reach a commercial scale, scientists and in-vitro meat developers are calling for sustained and increased investment so that research into refining production methods can be prioritised<font size="1"><sup>18,27</sup></font>. Researchers have also emphasised that technological assessments are necessary to highlight the challenges of integrating in-vitro meat into the existing food distribution system<font size="1"><sup>22</sup></font>.

Currently, a premarket safety assessment under the Novel Foods Regulation would be necessary before cultured meat could be legally marketed<font size="1"><sup>29</sup></font>. If approved, this would serve to define both conditions of use and labelling procedures<font size="1"><sup>29,30</sup></font>. However, as the food industry in the UK is mostly governed by EU law, the implications on existing novel food regulation of Britain leaving the EU are uncertain. However, Brexit may present opportunities for cultured meat products. Yet, given the infancy of cellular agriculture, new regulatory and classification frameworks may be necessary<font size="1"><sup>31</sup></font>. To increase chances of investment, in-vitro meat companies are suggesting the need for early involvement by regulatory bodies to ease the policy work required if cultured meat were to become commercially viable<font size="1"><sup>22</sup></font>.

Consumer acceptance is another concern for the prospect of in-vitro meat<font size="1"><sup>29</sup></font>. Questionnaires in the US and the Netherlands revealed 70% and 43% of participants would be keen to try in-vitro meat respectively<font size="1"><sup>32,33</sup></font>. However, the number of people willing to consume it regularly was substantially lower, with product appeal, safety and cost being the main concerns<font size="1"><sup>32</sup></font>. Since 2013, media and digital coverage of cultured meat has increased. For instance, TED talks<font size="1"><sup>34,35</sup></font>, a presentation at the World Economic Forum<font size="1"><sup>36</sup></font> and even a fictitious proof of concept restaurant ‘Bistro In Vitro’<font size="1"><sup>37</sup></font>, are available online. All serve as avenues to engage the public with the possibility of in-vitro meat and assess the potential impact on food culture. Researchers are calling for further studies and public engagement to identify potential barriers to future in-vitro meat consumption and possible marketing strategies<font size="1"><sup>27</sup></font>.

# conclusions

With the global population expected to reach 9 billion in 2050, global meat production is projected to more than double from 229 million tonnes in 2001, to 465 million tonnes in 2050<font size="1"><sup>38</sup></font>. It is therefore critical that alternative solutions to conventional meat production be explored that will address issues of food security whilst mitigating environmental and human health impacts. In-vitro meat could provide a promising solution, yet considerable research and funding is required before the product could become commercially available and socially acceptable to consumers.

<font size="2">
<br><b>References: </b><br>
1. FAO, 2006. <i>Livestock’s long shadow: environmental issues and options.</i> Rome, Italy. <br>
2. FAO, 2009. <i>How to feed the world in 2050.</i> Rome, Italy. <br>
3. Thornton PK, 2006. <i>Mapping climate vulnerability and poverty in Africa.</i> Nairobi, Kenya: IRLI. <br>
4. Thornton PK, 2010. <i>Livestock production: recent trends, future prospects.</i> Proc Royal Soc B 365, 2853–2867. <br>
5. Rosegrant MW <i>et al.</i>, 2009. <i>Looking into the future for agriculture and AKST (Agricultural Knowledge Science and Technology)</i>. In Agriculture at a crossroads, 307–376. Washington DC: Island Press. <br>
6. Public Health England, 2016. <i>The Eatwell Guide.</i> <br>
7. FAO, 2013. <i>Tackling climate change through livestock.</i> Rome, Italy. <br>
8. Warwick Crop Centre, 2012. <i>Technology to improve water use efficiency: Livestock report.</i> <br>
9. World Economic Forum, 2013. <i>Global Risks Report.</i> Geneva, Switzerland. <br>
10. Khachatourians GG, 1998. <i>Agricultural use of antibiotics and the evolution and transfer of antibiotic resistant bacteria.</i> CMAJ <b>159</b>, 1129–1136. <br>
11. DAERA, 2004. <i>Overview of Antimicrobial Usage and Bacterial Resistance in Selected Human and Animal
Pathogens in the UK.</i> Belfast, Northern Ireland. <br>
12. Smith GJD <i>et al.</i>, 2009. <i>Origins and evolutionary genomics of the 2009 swine-origin H1N1 influenza A epidemic.</i> Nature <b>459</b>, 1122–1125. <br>
13. Zhou L <i>et al.</i>, 2017. <i>Sudden increase in human infection with avian influenza A (H7N9) virus in China, September-December 2016.</i> Western Pacific Surveillance and Response Journal <b>9</b>:1 <br>
14. House of Lords, 2011. 19th Report of Session 2010-12: <i>Innovation in EU agriculture.</i> <br>
15. Moritz MSM <i>et al.</i>, 2015. <i>Alternatives for large-scale production of cultured beef.</i> Journal of Integrative Agriculture <b>14</b>, 208–216. <br>
16. Post MJ, 2012. <i>Cultured meat from stem cells: Challenges and prospects.</i> Meat Science 92, 297–301. <br>
17. Datar I <i>et al.</i>, 2010. <i>Possibilities for an in vitro meat production system.</i> Innovative Food Science & Emerging Technologies 11, 13–22. <br>
18. Bhat ZF <i>et al.</i>, 2011. <i>Prospectus of cultured meat – advancing meat alternatives.</i> Journal of Food Science and Technology <b>48</b>, 125-140. <br>
19. Tuomisto HL & Teixeira de Mattos MJ, 2011. <i>Environmental Impacts of Cultured Meat Production.</i> Environmental Science and Technology <b>45</b>, 6117–6123. <br>
20. Mattick CS <i>et al.</i>, 2015. <i>Anticipatory Life Cycle Analysis of In Vitro Biomass Cultivation for Cultured Meat Production in the United States.</i> Environmental Science and Technology <b>49</b>, 11941–9. <br>
21. Tuomisto HL & Roy AG, 2012. <i>Could cultured meat reduce environmental impact of agriculture in Europe?</i> Proceedings of the 8th International Conference on Life Cycle Assessment in the Agri-Food Sector, 615-619. <br>
22. The EPINET Consortium, 2013. <i>Policy Recommendations: Synthetic Meat.</i> Bergen, Norway. <br>
23. <a href="http://www.memphismeats.com">Memphis Meats</a> <br>
24. <a href="http://supermeat.com">SuperMeat</a> <br>
25. <a href="http://culturedbeef.org">Cultured Meat: Maastricht University</a> <br>
26. Memphis Meats, 2017. <a href="http://goo.gl/HiuhSS">Press Release: Memphis Meats announces world’s first ‘clean poultry.’</a> <br>
27. Sam Harris, 2016. <a href="http://goo.gl/qDF9zi">Meat without misery: A conversation with Uma Valeti.</a> <br>
28. Parliamentary Office of Science and Technology, 2015. <i>Novel Food Production.</i> <br>
29. FSA, 2011. <i>Emerging food technologies: Novel protein sources as food.</i> London, UK. <br>
30. Regulation (EC) No 258/97 of the European Parliament and of the Council of 27 January 1997 concerning novel foods and novel food ingredients. <br>
31. Sentience Politics, 2016. <i>Cultured Meat.</i> Berlin, Germany. <br>
32. Wilks M & Phillips CJC, 2017. <i>Attitudes to in vitro meat: A survey of potential consumers in the United
States.</i> PLoS ONE <b>12</b>(2): e0171904. <br>
33. Verbeke W <i>et al.</i>, 2015. <i>Challenges and prospects for consumer acceptance of cultured meat.</i> Journal of Integrative Agriculture. <b>14</b>, 285–294. <br>
34. Post M, 2013. <i>Meet the new meat</i>. <a href="http://goo.gl/5ZyNYN">TEDx Talk.</a> <br> 
35. Datar I, 2013. <i>Re-Thinking Meat</i>. <a href="http://goo.gl/Q1AqH6">TEDx Talk.</a> <br> 
36. Post M, 2015. <a href="http://goo.gl/yIG5Zl">The Meat Revolution.</a> World Economic Forum. <br> 
37. <a href="http://bistro-invitro.com/en/bistro-invitro">Bistro In Vitro</a> <br>
38. FAO, 2006. <i>World agriculture: towards 2030/2050.</i> Interim Report. Rome, Italy.<br>
</font>

